<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use DB;

class ItemPerintahSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('item_perintahs')->insert([

            // --> KATEGORI UMUR 0-3 BULAN <-- 
            [
                'id' => '1',
                'perintah' => 'Mengangkat kepala 45 derajat',
                'aspek_perkembangan_id' => '1',
                'kategori_umur_id' => '1',
            ],
            [
                'id' => '2',
                'perintah' => 'Menahan kepala tetap tegak',
                'aspek_perkembangan_id' => '1',
                'kategori_umur_id' => '1',
            ],
            [
                'id' => '3',
                'perintah' => 'Menggerakkan kepala dari kiri/kanan ke tengah',
                'aspek_perkembangan_id' => '1',
                'kategori_umur_id' => '1',
            ],
            [
                'id' => '4',
                'perintah' => 'Belajar tengkurap',
                'aspek_perkembangan_id' => '1',
                'kategori_umur_id' => '1',
            ],
            [
                'id' => '5',
                'perintah' => 'Melihat dan mentap benda',
                'aspek_perkembangan_id' => '2',
                'kategori_umur_id' => '1',
            ],
            [
                'id' => '6',
                'perintah' => 'Melihat dan menatap wajah anda',
                'aspek_perkembangan_id' => '2',
                'kategori_umur_id' => '1',
            ],
            [
                'id' => '7',
                'perintah' => 'Meraba dan memegang benda',
                'aspek_perkembangan_id' => '2',
                'kategori_umur_id' => '1',
            ],
            [
                'id' => '8',
                'perintah' => 'Ajak bayi tersenyum',
                'aspek_perkembangan_id' => '3',
                'kategori_umur_id' => '1',
            ],
            [
                'id' => '9',
                'perintah' => 'Berbicara setiap hari',
                'aspek_perkembangan_id' => '3',
                'kategori_umur_id' => '1',
            ],
            [
                'id' => '10',
                'perintah' => 'Mengenali berbagai suara',
                'aspek_perkembangan_id' => '3',
                'kategori_umur_id' => '1',
            ],
            [
                'id' => '11',
                'perintah' => 'Bayi sebaiknya tidak dikenalkan pada televisi atau gawai hingga usia 2 tahun',
                'aspek_perkembangan_id' => '3',
                'kategori_umur_id' => '1',
            ],
            [
                'id' => '12',
                'perintah' => 'Bercakap-cakap',
                'aspek_perkembangan_id' => '3',
                'kategori_umur_id' => '1',
            ],
            [
                'id' => '13',
                'perintah' => 'Memberi rasa aman dan kasih sayang',
                'aspek_perkembangan_id' => '4',
                'kategori_umur_id' => '1',
            ],
            [
                'id' => '14',
                'perintah' => 'Meninabobokkan bayi',
                'aspek_perkembangan_id' => '4',
                'kategori_umur_id' => '1',
            ],
            [
                'id' => '15',
                'perintah' => 'Meniru ocehan dan mimik muka bayi',
                'aspek_perkembangan_id' => '4',
                'kategori_umur_id' => '1',
            ],
            [
                'id' => '16',
                'perintah' => 'Mengayun bayi',
                'aspek_perkembangan_id' => '4',
                'kategori_umur_id' => '1',
            ],
            [
                'id' => '17',
                'perintah' => 'Mengajak bayi tersenyum',
                'aspek_perkembangan_id' => '4',
                'kategori_umur_id' => '1',
            ],
            [
                'id' => '18',
                'perintah' => 'Mengajak bayi mengamati benda-benda dan keadaan sekitarnya',
                'aspek_perkembangan_id' => '4',
                'kategori_umur_id' => '1',
            ],

             // --> KATEGORI UMUR 3-6 BULAN <--
            [
                'id' => '19',
                'perintah' => 'Lanjutkan stimulasi untuk menehan kepala setiap tegak',
                'aspek_perkembangan_id' => '1',
                'kategori_umur_id' => '2',
            ],
            [
                'id' => '20',
                'perintah' => 'Belajar tengkurap',
                'aspek_perkembangan_id' => '1',
                'kategori_umur_id' => '2',
            ],
            [
                'id' => '21',
                'perintah' => 'Menyangga berat badan',
                'aspek_perkembangan_id' => '1',
                'kategori_umur_id' => '2',
            ],
            [
                'id' => '22',
                'perintah' => 'Mengembangkan kontrol terhadap kepala',
                'aspek_perkembangan_id' => '1',
                'kategori_umur_id' => '2',
            ],
            [
                'id' => '23',
                'perintah' => 'Belajar posisi duduk',
                'aspek_perkembangan_id' => '1',
                'kategori_umur_id' => '2',
            ],
            [
                'id' => '24',
                'perintah' => 'Lanjutkan stimulasi melihat dan menatap benda dan wajah serta meraba dan memegang benda',
                'aspek_perkembangan_id' => '2',
                'kategori_umur_id' => '2',
            ],
            [
                'id' => '25',
                'perintah' => 'Memegang benda dengan kuat',
                'aspek_perkembangan_id' => '2',
                'kategori_umur_id' => '2',
            ],
            [
                'id' => '26',
                'perintah' => 'Memegang benda dengan kedua tangan',
                'aspek_perkembangan_id' => '2',
                'kategori_umur_id' => '2',
            ],
            [
                'id' => '27',
                'perintah' => 'Mengambil benda kecil',
                'aspek_perkembangan_id' => '2',
                'kategori_umur_id' => '2',
            ],
            [
                'id' => '28',
                'perintah' => 'Mengarahkan pandangan ke benda-benda kecil',
                'aspek_perkembangan_id' => '2',
                'kategori_umur_id' => '2',
            ],
            [
                'id' => '29',
                'perintah' => 'Lanjutkan stimulasi berbicara, bercakap-cakap dan memperkenalkan bayi dengan berbagai suara',
                'aspek_perkembangan_id' => '3',
                'kategori_umur_id' => '2',
            ],
            [
                'id' => '30',
                'perintah' => 'Mencari sumber suara',
                'aspek_perkembangan_id' => '3',
                'kategori_umur_id' => '2',
            ],
            [
                'id' => '31',
                'perintah' => 'Menirukan kata-kata',
                'aspek_perkembangan_id' => '3',
                'kategori_umur_id' => '2',
            ],
            [
                'id' => '32',
                'perintah' => 'Lanjutkan stimulasi memberi rasa aman dan kasih sayang, menganjak bayi tersenyum, mengayun, meninabobokkan dan mengamati benda sekitar',
                'aspek_perkembangan_id' => '4',
                'kategori_umur_id' => '2',
            ],
            [
                'id' => '33',
                'perintah' => 'Bermain cilukba',
                'aspek_perkembangan_id' => '4',
                'kategori_umur_id' => '2',
            ],
            [
                'id' => '34',
                'perintah' => 'Melihat dirinya dicermin',
                'aspek_perkembangan_id' => '4',
                'kategori_umur_id' => '2',
            ],
            [
                'id' => '35',
                'perintah' => 'Berusaha meraih mainan',
                'aspek_perkembangan_id' => '4',
                'kategori_umur_id' => '2',
            ],

            // --> KATEGORI UMUR 6-9 BULAN <--
            [
                'id' => '36',
                'perintah' => 'Lanjutkan stimulasi menyangga berat badan, mengembangkan kontrol kepala, dan belajar posisi duduk',
                'aspek_perkembangan_id' => '1',
                'kategori_umur_id' => '3',
            ],
            [
                'id' => '37',
                'perintah' => 'Belajar duduk',
                'aspek_perkembangan_id' => '1',
                'kategori_umur_id' => '3',
            ],
            [
                'id' => '38',
                'perintah' => 'Belajar berdiri',
                'aspek_perkembangan_id' => '1',
                'kategori_umur_id' => '3',
            ],
            [
                'id' => '39',
                'perintah' => 'Belajar berpegangan',
                'aspek_perkembangan_id' => '1',
                'kategori_umur_id' => '3',
            ],
            [
                'id' => '40',
                'perintah' => 'Belajar dengan bantuan',
                'aspek_perkembangan_id' => '1',
                'kategori_umur_id' => '3',
            ],
            [
                'id' => '41',
                'perintah' => 'Merangkak untuk mengambil mainan',
                'aspek_perkembangan_id' => '1',
                'kategori_umur_id' => '3',
            ],
            [
                'id' => '42',
                'perintah' => 'Lanjutkkan stimulasi memegang benda dengan kuat, memegang benda dengan kedua tangan dan mengambil benda kecil',
                'aspek_perkembangan_id' => '2',
                'kategori_umur_id' => '3',
            ],
            [
                'id' => '43',
                'perintah' => 'Bermain tabuh gendang',
                'aspek_perkembangan_id' => '2',
                'kategori_umur_id' => '3',
            ],
            [
                'id' => '44',
                'perintah' => 'Memegang alat tulis dan mencoret-coret',
                'aspek_perkembangan_id' => '2',
                'kategori_umur_id' => '3',
            ],
            [
                'id' => '45',
                'perintah' => 'Bermain mainan yang mengapung di air',
                'aspek_perkembangan_id' => '2',
                'kategori_umur_id' => '3',
            ],
            [
                'id' => '46',
                'perintah' => 'Menyembunyikan dan mencari mainan',
                'aspek_perkembangan_id' => '2',
                'kategori_umur_id' => '3',
            ],
            [
                'id' => '47',
                'perintah' => 'Memindahkan benda dari satu tangan ke tangan lainnya',
                'aspek_perkembangan_id' => '2',
                'kategori_umur_id' => '3',
            ],
            [
                'id' => '48',
                'perintah' => 'Memasukkan benda ke dalam wadah',
                'aspek_perkembangan_id' => '2',
                'kategori_umur_id' => '3',
            ],
            [
                'id' => '49',
                'perintah' => 'Membuat bunyi-bunyian',
                'aspek_perkembangan_id' => '2',
                'kategori_umur_id' => '3',
            ],
            [
                'id' => '50',
                'perintah' => 'Lanjutkkan stimulasi berbicara, mengenali suara mencari sumber suara meniru kata-kata',
                'aspek_perkembangan_id' => '3',
                'kategori_umur_id' => '3',
            ],
            [
                'id' => '51',
                'perintah' => 'Menyebutkan nama gambar di buku',
                'aspek_perkembangan_id' => '3',
                'kategori_umur_id' => '3',
            ],
            [
                'id' => '52',
                'perintah' => 'Menunjukkan dan menyebutkan nama gambar',
                'aspek_perkembangan_id' => '3',
                'kategori_umur_id' => '3',
            ],
            [
                'id' => '53',
                'perintah' => 'Lanjutkkan stimulasi sebelumnya',
                'aspek_perkembangan_id' => '4',
                'kategori_umur_id' => '3',
            ],
            [
                'id' => '54',
                'perintah' => 'Melambai "dadah"',
                'aspek_perkembangan_id' => '4',
                'kategori_umur_id' => '3',
            ],
            [
                'id' => '55',
                'perintah' => 'Ajak bayi bermain bersama orang lain',
                'aspek_perkembangan_id' => '4',
                'kategori_umur_id' => '3',
            ],

            // --> KATEGORI UMUR 9-12 BULAN <--
            [
                'id' => '56',
                'perintah' => 'Menyusun balok/kotak',
                'aspek_perkembangan_id' => '2',
                'kategori_umur_id' => '4',
            ],
            [
                'id' => '57',
                'perintah' => 'Menggambar',
                'aspek_perkembangan_id' => '2',
                'kategori_umur_id' => '4',
            ],
            [
                'id' => '58',
                'perintah' => 'Bermain di dapur',
                'aspek_perkembangan_id' => '2',
                'kategori_umur_id' => '4',
            ],
            [
                'id' => '59',
                'perintah' => 'Menirukan kata-kata',
                'aspek_perkembangan_id' => '3',
                'kategori_umur_id' => '4',
            ],
            [
                'id' => '60',
                'perintah' => 'Berbicara dengan boneka atau anggota keluarga lain',
                'aspek_perkembangan_id' => '3',
                'kategori_umur_id' => '4',
            ],
            [
                'id' => '61',
                'perintah' => 'Bersenandung dan bernyanyi',
                'aspek_perkembangan_id' => '3',
                'kategori_umur_id' => '4',
            ],
            [
                'id' => '62',
                'perintah' => 'Mainan yang dapat ditarik',
                'aspek_perkembangan_id' => '4',
                'kategori_umur_id' => '4',
            ],
            [
                'id' => '63',
                'perintah' => 'Bermain cilukba dengan anggota keluarga lain',
                'aspek_perkembangan_id' => '4',
                'kategori_umur_id' => '4',
            ],
            [
                'id' => '64',
                'perintah' => 'Melambai dadah dengan orang lain',
                'aspek_perkembangan_id' => '4',
                'kategori_umur_id' => '4',
            ],
            [
                'id' => '65',
                'perintah' => 'Belajar bersosialisasi dengan lingkungan (salam, melambai, dadah dan bermain bersama)',
                'aspek_perkembangan_id' => '4',
                'kategori_umur_id' => '4',
            ],

             // --> KATEGORI UMUR 12-18 BULAN <--
            [
                'id' => '66',
                'perintah' => 'Berjalan mundur 5 langkah',
                'aspek_perkembangan_id' => '1',
                'kategori_umur_id' => '5',
            ],
            [
                'id' => '67',
                'perintah' => 'Menarik mainan',
                'aspek_perkembangan_id' => '1',
                'kategori_umur_id' => '5',
            ],
            [
                'id' => '68',
                'perintah' => 'Membungkuk memungut mainan kemudian berdiri kembali',
                'aspek_perkembangan_id' => '1',
                'kategori_umur_id' => '5',
            ],
            [
                'id' => '69',
                'perintah' => 'Berjalan naik dan turun tangga',
                'aspek_perkembangan_id' => '1',
                'kategori_umur_id' => '5',
            ],
            [
                'id' => '70',
                'perintah' => 'Berjalan sambil berjinjit',
                'aspek_perkembangan_id' => '1',
                'kategori_umur_id' => '5',
            ],
            [
                'id' => '71',
                'perintah' => 'Menangkap dan melempar bola',
                'aspek_perkembangan_id' => '1',
                'kategori_umur_id' => '5',
            ],
            [
                'id' => '72',
                'perintah' => 'Permainan balok',
                'aspek_perkembangan_id' => '2',
                'kategori_umur_id' => '5',
            ],
            [
                'id' => '73',
                'perintah' => 'Memasukkan dan mengeluarkan benda',
                'aspek_perkembangan_id' => '2',
                'kategori_umur_id' => '5',
            ],
            [
                'id' => '74',
                'perintah' => 'Memindahkan benda',
                'aspek_perkembangan_id' => '2',
                'kategori_umur_id' => '5',
            ],
            [
                'id' => '75',
                'perintah' => 'Membuat suara',
                'aspek_perkembangan_id' => '3',
                'kategori_umur_id' => '5',
            ],
            [
                'id' => '76',
                'perintah' => 'Menirukan pekerjaan rumah tangga',
                'aspek_perkembangan_id' => '4',
                'kategori_umur_id' => '5',
            ],
            [
                'id' => '77',
                'perintah' => 'Melepaskan pakaian',
                'aspek_perkembangan_id' => '4',
                'kategori_umur_id' => '5',
            ],
            [
                'id' => '78',
                'perintah' => 'Makan sendiri',
                'aspek_perkembangan_id' => '4',
                'kategori_umur_id' => '5',
            ],
            [
                'id' => '79',
                'perintah' => 'Merawat boneka',
                'aspek_perkembangan_id' => '4',
                'kategori_umur_id' => '5',
            ],
            [
                'id' => '80',
                'perintah' => 'Mengunjungi tempat umum',
                'aspek_perkembangan_id' => '4',
                'kategori_umur_id' => '5',
            ],

            // --> KATEGORI UMUR 18-24 BULAN <--
            [
                'id' => '81',
                'perintah' => 'Dorong agar anak mau berlari, berjalan dengan berjinjit, bermain di air, menendang, melempar dan menangkap bola besar serta berjalan turun tangga',
                'aspek_perkembangan_id' => '1',
                'kategori_umur_id' => '6',
            ],
            [
                'id' => '82',
                'perintah' => 'Berjalan tanpa terhuyung-huyung',
                'aspek_perkembangan_id' => '1',
                'kategori_umur_id' => '6',
            ],
            [
                'id' => '83',
                'perintah' => 'Melatih keseimbangan tubuh',
                'aspek_perkembangan_id' => '1',
                'kategori_umur_id' => '6',
            ],
            [
                'id' => '84',
                'perintah' => 'Mendorong mainan dengan kaki',
                'aspek_perkembangan_id' => '1',
                'kategori_umur_id' => '6',
            ],
            [
                'id' => '85',
                'perintah' => 'Mengenal berbagai ukuran dan bentuk',
                'aspek_perkembangan_id' => '2',
                'kategori_umur_id' => '6',
            ],
            [
                'id' => '86',
                'perintah' => 'Bermain puzzle',
                'aspek_perkembangan_id' => '2',
                'kategori_umur_id' => '6',
            ],
            [
                'id' => '87',
                'perintah' => 'Menggambar wajah atau bentuk',
                'aspek_perkembangan_id' => '2',
                'kategori_umur_id' => '6',
            ],
            [
                'id' => '88',
                'perintah' => 'Membuat berbagai bentuk dari adonan kue atau lilin mainan',
                'aspek_perkembangan_id' => '2',
                'kategori_umur_id' => '6',
            ],
            [
                'id' => '89',
                'perintah' => 'Mengerjakan perintah sederhana',
                'aspek_perkembangan_id' => '3',
                'kategori_umur_id' => '6',
            ],
            [
                'id' => '90',
                'perintah' => 'Bercerita tentang apa yang dilihat',
                'aspek_perkembangan_id' => '3',
                'kategori_umur_id' => '6',
            ],
            [
                'id' => '91',
                'perintah' => 'Bujuk dan tenangkan anak ketika rewel',
                'aspek_perkembangan_id' => '4',
                'kategori_umur_id' => '6',
            ],
            [
                'id' => '92',
                'perintah' => 'Belajar melepas baju sendiri',
                'aspek_perkembangan_id' => '4',
                'kategori_umur_id' => '6',
            ],
            [
                'id' => '93',
                'perintah' => 'Belajar makan pakai sendok dan garpu',
                'aspek_perkembangan_id' => '4',
                'kategori_umur_id' => '6',
            ],
            [
                'id' => '94',
                'perintah' => 'Permainan yang memerlukan interaksi dengan teman',
                'aspek_perkembangan_id' => '4',
                'kategori_umur_id' => '6',
            ],
            [
                'id' => '95',
                'perintah' => 'Membuat rumah-rumahan',
                'aspek_perkembangan_id' => '4',
                'kategori_umur_id' => '6',
            ],
            [
                'id' => '96',
                'perintah' => 'Berpakaian',
                'aspek_perkembangan_id' => '4',
                'kategori_umur_id' => '6',
            ],
            [
                'id' => '97',
                'perintah' => 'Perkenalkan awal jenis kelamin kepada anak',
                'aspek_perkembangan_id' => '4',
                'kategori_umur_id' => '6',
            ],

            // --> KATEGORI UMUR 24-36 BULAN <--
            [
                'id' => '98',
                'perintah' => 'Aktifitas fisik (memanjat, melompat, berlari)',
                'aspek_perkembangan_id' => '1',
                'kategori_umur_id' => '7',
            ],
            [
                'id' => '99',
                'perintah' => 'Latihan menghadapi rintangan',
                'aspek_perkembangan_id' => '1',
                'kategori_umur_id' => '7',
            ],
            [
                'id' => '100',
                'perintah' => 'Melompat jauh dengan kedua kaki bersamaan',
                'aspek_perkembangan_id' => '1',
                'kategori_umur_id' => '7',
            ],
            [
                'id' => '101',
                'perintah' => 'Melempar dan menangkap',
                'aspek_perkembangan_id' => '1',
                'kategori_umur_id' => '7',
            ],
            [
                'id' => '102',
                'perintah' => 'Mencoret-coret kertas',
                'aspek_perkembangan_id' => '2',
                'kategori_umur_id' => '7',
            ],
            [
                'id' => '103',
                'perintah' => 'Membuat gambar tempelan',
                'aspek_perkembangan_id' => '2',
                'kategori_umur_id' => '7',
            ],
            [
                'id' => '104',
                'perintah' => 'Memilih dan mengelompokkan benda-benda menurut jenisnya',
                'aspek_perkembangan_id' => '2',
                'kategori_umur_id' => '7',
            ],
            [
                'id' => '105',
                'perintah' => 'Mencocokkan gambar dan benda',
                'aspek_perkembangan_id' => '2',
                'kategori_umur_id' => '7',
            ],
            [
                'id' => '106',
                'perintah' => 'Konsep jumlah',
                'aspek_perkembangan_id' => '2',
                'kategori_umur_id' => '7',
            ],
            [
                'id' => '107',
                'perintah' => 'Menyusun balok',
                'aspek_perkembangan_id' => '2',
                'kategori_umur_id' => '7',
            ],
            [
                'id' => '108',
                'perintah' => 'Ajak berbicara',
                'aspek_perkembangan_id' => '3',
                'kategori_umur_id' => '7',
            ],
            [
                'id' => '109',
                'perintah' => 'Bacakan buku cerita anak',
                'aspek_perkembangan_id' => '3',
                'kategori_umur_id' => '7',
            ],
            [
                'id' => '110',
                'perintah' => 'Dengarkan cerita anak',
                'aspek_perkembangan_id' => '3',
                'kategori_umur_id' => '7',
            ],
            [
                'id' => '111',
                'perintah' => 'Batasi waktu menonton maksimal 1 jam sehari',
                'aspek_perkembangan_id' => '3',
                'kategori_umur_id' => '7',
            ],
            [
                'id' => '112',
                'perintah' => 'Menyebut nama lengkap anak',
                'aspek_perkembangan_id' => '3',
                'kategori_umur_id' => '7',
            ],
            [
                'id' => '113',
                'perintah' => 'Bercerita tentang diri anak',
                'aspek_perkembangan_id' => '3',
                'kategori_umur_id' => '7',
            ],
            [
                'id' => '114',
                'perintah' => 'Melihat gambar dan dapat menyebut dengan benar nama 2 benda atau lebih',
                'aspek_perkembangan_id' => '3',
                'kategori_umur_id' => '7',
            ],
            [
                'id' => '115',
                'perintah' => 'Menyebut jenis pakaian',
                'aspek_perkembangan_id' => '3',
                'kategori_umur_id' => '7',
            ],
            [
                'id' => '116',
                'perintah' => 'Menyatakan keadaan suatu benda',
                'aspek_perkembangan_id' => '3',
                'kategori_umur_id' => '7',
            ],
            [
                'id' => '117',
                'perintah' => 'Belajar makan sendiri tanpa banyak tumpah',
                'aspek_perkembangan_id' => '4',
                'kategori_umur_id' => '7',
            ],
            [
                'id' => '118',
                'perintah' => 'Melepas pakaian sendiri',
                'aspek_perkembangan_id' => '4',
                'kategori_umur_id' => '7',
            ],
            [
                'id' => '119',
                'perintah' => 'Melatih buang air kecil dan buang air besar di kamar mandi/WC',
                'aspek_perkembangan_id' => '4',
                'kategori_umur_id' => '7',
            ],
            [
                'id' => '120',
                'perintah' => 'Berpakaian',
                'aspek_perkembangan_id' => '4',
                'kategori_umur_id' => '7',
            ],
            [
                'id' => '121',
                'perintah' => 'Bujuk dan tenangkan ketika anak kecewa dengan cara memeluk dan berbicara kepadanya',
                'aspek_perkembangan_id' => '4',
                'kategori_umur_id' => '7',
            ],
            [
                'id' => '122',
                'perintah' => 'Berdandan',
                'aspek_perkembangan_id' => '4',
                'kategori_umur_id' => '7',
            ],
            [
                'id' => '123',
                'perintah' => 'Menekankan konsep kebersihan',
                'aspek_perkembangan_id' => '4',
                'kategori_umur_id' => '7',
            ],
          
             // --> KATEGORI UMUR 36-48 BULAN <--
            [
                'id' => '124',
                'perintah' => 'Dorong anak beraktifitas fisik',
                'aspek_perkembangan_id' => '1',
                'kategori_umur_id' => '8',
            ],
            [
                'id' => '125',
                'perintah' => 'Lomba karung',
                'aspek_perkembangan_id' => '1',
                'kategori_umur_id' => '8',
            ],
            [
                'id' => '126',
                'perintah' => 'Main engklek',
                'aspek_perkembangan_id' => '1',
                'kategori_umur_id' => '8',
            ],
            [
                'id' => '127',
                'perintah' => 'Melompati tali',
                'aspek_perkembangan_id' => '1',
                'kategori_umur_id' => '8',
            ],
            [
                'id' => '128',
                'perintah' => 'Menari',
                'aspek_perkembangan_id' => '2',
                'kategori_umur_id' => '8',
            ],
            [
                'id' => '129',
                'perintah' => 'Menggambar tanda silang, lingkaran orang mengancing baju',
                'aspek_perkembangan_id' => '2',
                'kategori_umur_id' => '8',
            ],
            [
                'id' => '130',
                'perintah' => 'Menggambar',
                'aspek_perkembangan_id' => '2',
                'kategori_umur_id' => '8',
            ],
            [
                'id' => '131',
                'perintah' => 'Mencocokkan dan menghitung',
                'aspek_perkembangan_id' => '2',
                'kategori_umur_id' => '8',
            ],
            [
                'id' => '132',
                'perintah' => 'Menggunting',
                'aspek_perkembangan_id' => '2',
                'kategori_umur_id' => '8',
            ],
            [
                'id' => '133',
                'perintah' => 'Membandingkan besar/kecil, banyak/sedikit, berat/ringan',
                'aspek_perkembangan_id' => '2',
                'kategori_umur_id' => '8',
            ],
            [
                'id' => '134',
                'perintah' => 'Percobaan ilmiah',
                'aspek_perkembangan_id' => '2',
                'kategori_umur_id' => '8',
            ],
            [
                'id' => '135',
                'perintah' => 'Berkebun',
                'aspek_perkembangan_id' => '2',
                'kategori_umur_id' => '8',
            ],
            [
                'id' => '136',
                'perintah' => 'Mengelompokkan benda dan foto',
                'aspek_perkembangan_id' => '2',
                'kategori_umur_id' => '8',
            ],
            [
                'id' => '137',
                'perintah' => 'Menyebutkan nama dengan lengkap tanpa dibantu',
                'aspek_perkembangan_id' => '3',
                'kategori_umur_id' => '8',
            ],
            [
                'id' => '138',
                'perintah' => 'Menyebutkan angka, menghitung jari',
                'aspek_perkembangan_id' => '3',
                'kategori_umur_id' => '8',
            ],
            [
                'id' => '139',
                'perintah' => 'Menyebut nama-nama hari',
                'aspek_perkembangan_id' => '3',
                'kategori_umur_id' => '8',
            ],
            [
                'id' => '140',
                'perintah' => 'Buku kegiatan keluarga',
                'aspek_perkembangan_id' => '3',
                'kategori_umur_id' => '8',
            ],
            [
                'id' => '141',
                'perintah' => 'Mengenal huruf dan simbol',
                'aspek_perkembangan_id' => '3',
                'kategori_umur_id' => '8',
            ],
            [
                'id' => '142',
                'perintah' => 'Belajar mengingat-ingat',
                'aspek_perkembangan_id' => '3',
                'kategori_umur_id' => '8',
            ],
            [
                'id' => '143',
                'perintah' => 'Melengkapi kalimat',
                'aspek_perkembangan_id' => '3',
                'kategori_umur_id' => '8',
            ],
            [
                'id' => '144',
                'perintah' => 'Bercerita masa kecil',
                'aspek_perkembangan_id' => '3',
                'kategori_umur_id' => '8',
            ],
            [
                'id' => '145',
                'perintah' => 'Mengenal angka',
                'aspek_perkembangan_id' => '3',
                'kategori_umur_id' => '8',
            ],
            [
                'id' => '146',
                'perintah' => 'Mendorong anak bercerita',
                'aspek_perkembangan_id' => '3',
                'kategori_umur_id' => '8',
            ],
            [
                'id' => '147',
                'perintah' => 'Memupuk keinginan membaca anak',
                'aspek_perkembangan_id' => '3',
                'kategori_umur_id' => '8',
            ],
            [
                'id' => '148',
                'perintah' => 'Mengenal musim',
                'aspek_perkembangan_id' => '3',
                'kategori_umur_id' => '8',
            ],
            [
                'id' => '149',
                'perintah' => 'Membantu pekerjaan di dapur',
                'aspek_perkembangan_id' => '3',
                'kategori_umur_id' => '8',
            ],
            [
                'id' => '150',
                'perintah' => 'Berpakaian sendiri tanpa dibantu',
                'aspek_perkembangan_id' => '4',
                'kategori_umur_id' => '8',
            ],
            [
                'id' => '151',
                'perintah' => 'Berperan dalam tugas rumah',
                'aspek_perkembangan_id' => '4',
                'kategori_umur_id' => '8',
            ],
            [
                'id' => '152',
                'perintah' => 'Interaksi teman sebaya',
                'aspek_perkembangan_id' => '4',
                'kategori_umur_id' => '8',
            ],
            [
                'id' => '153',
                'perintah' => 'Mendengar cerita anak',
                'aspek_perkembangan_id' => '4',
                'kategori_umur_id' => '8',
            ],
            [
                'id' => '154',
                'perintah' => 'Buat rencana jalan-jalan',
                'aspek_perkembangan_id' => '4',
                'kategori_umur_id' => '8',
            ],
            [
                'id' => '155',
                'perintah' => 'Mengikuti aturan/petunjuk permainan',
                'aspek_perkembangan_id' => '4',
                'kategori_umur_id' => '8',
            ],
            [
                'id' => '156',
                'perintah' => 'Membuat album kelurga',
                'aspek_perkembangan_id' => '4',
                'kategori_umur_id' => '8',
            ],
            [
                'id' => '157',
                'perintah' => 'Membuat boneka',
                'aspek_perkembangan_id' => '4',
                'kategori_umur_id' => '8',
            ],
            [
                'id' => '158',
                'perintah' => 'Menggambar orang',
                'aspek_perkembangan_id' => '4',
                'kategori_umur_id' => '8',
            ],
            [
                'id' => '159',
                'perintah' => 'Bermain kreatif dengan teman',
                'aspek_perkembangan_id' => '4',
                'kategori_umur_id' => '8',
            ],
            [
                'id' => '160',
                'perintah' => 'Bermain jual beli',
                'aspek_perkembangan_id' => '4',
                'kategori_umur_id' => '8',
            ],

            // --> KATEGORI UMUR 48-60 BULAN <--
            [
                'id' => '161',
                'perintah' => 'Dorong anak berkreativitas fisik',
                'aspek_perkembangan_id' => '1',
                'kategori_umur_id' => '9',
            ],
            [
                'id' => '162',
                'perintah' => 'Lomba karung',
                'aspek_perkembangan_id' => '1',
                'kategori_umur_id' => '9',
            ],
            [
                'id' => '163',
                'perintah' => 'Main engklek',
                'aspek_perkembangan_id' => '1',
                'kategori_umur_id' => '9',
            ],
            [
                'id' => '164',
                'perintah' => 'Melompat tali',
                'aspek_perkembangan_id' => '1',
                'kategori_umur_id' => '9',
            ],
            [
                'id' => '165',
                'perintah' => 'Menari',
                'aspek_perkembangan_id' => '2',
                'kategori_umur_id' => '9',
            ],
            [
                'id' => '166',
                'perintah' => 'Menggambar tanda silang, lingkaran, orang, mengancing baju',
                'aspek_perkembangan_id' => '2',
                'kategori_umur_id' => '9',
            ],
            [
                'id' => '167',
                'perintah' => 'Menggambar',
                'aspek_perkembangan_id' => '2',
                'kategori_umur_id' => '9',
            ],
            [
                'id' => '168',
                'perintah' => 'Mencocokkan dan menghitung',
                'aspek_perkembangan_id' => '2',
                'kategori_umur_id' => '9',
            ],
            [
                'id' => '169',
                'perintah' => 'Menggunting',
                'aspek_perkembangan_id' => '2',
                'kategori_umur_id' => '9',
            ],
            [
                'id' => '170',
                'perintah' => 'Membandingkan besar/kecil, banyak/sedikit, berat/ringan',
                'aspek_perkembangan_id' => '2',
                'kategori_umur_id' => '9',
            ],
            [
                'id' => '171',
                'perintah' => 'Percobaan ilmiah',
                'aspek_perkembangan_id' => '2',
                'kategori_umur_id' => '9',
            ],
            [
                'id' => '172',
                'perintah' => 'Berkebun',
                'aspek_perkembangan_id' => '2',
                'kategori_umur_id' => '9',
            ],
            [
                'id' => '173',
                'perintah' => 'Mengelompokkan benda dan foto',
                'aspek_perkembangan_id' => '2',
                'kategori_umur_id' => '9',
            ],
            [
                'id' => '174',
                'perintah' => 'Menyebutkan nama lengkap tanpa dibantu',
                'aspek_perkembangan_id' => '3',
                'kategori_umur_id' => '9',
            ],
            [
                'id' => '175',
                'perintah' => 'Menyebut angka dan menghitung jari',
                'aspek_perkembangan_id' => '3',
                'kategori_umur_id' => '9',
            ],
            [
                'id' => '176',
                'perintah' => 'Buku kegiatan keluarga',
                'aspek_perkembangan_id' => '3',
                'kategori_umur_id' => '9',
            ],
            [
                'id' => '177',
                'perintah' => 'Mengenal huruf dan simbol',
                'aspek_perkembangan_id' => '3',
                'kategori_umur_id' => '9',
            ],
            [
                'id' => '178',
                'perintah' => 'Belajar mengingat-ingat',
                'aspek_perkembangan_id' => '3',
                'kategori_umur_id' => '9',
            ],
            [
                'id' => '179',
                'perintah' => 'Melengkapi kalimat',
                'aspek_perkembangan_id' => '3',
                'kategori_umur_id' => '9',
            ],
            [
                'id' => '180',
                'perintah' => 'Bercerita masa kecil',
                'aspek_perkembangan_id' => '3',
                'kategori_umur_id' => '9',
            ],
            [
                'id' => '181',
                'perintah' => 'Mengenal angka',
                'aspek_perkembangan_id' => '3',
                'kategori_umur_id' => '9',
            ],
            [
                'id' => '182',
                'perintah' => 'Mendorong anak bercerita',
                'aspek_perkembangan_id' => '3',
                'kategori_umur_id' => '9',
            ],
            [
                'id' => '183',
                'perintah' => 'Memupuk keinginan membaca anak',
                'aspek_perkembangan_id' => '3',
                'kategori_umur_id' => '9',
            ],
            [
                'id' => '184',
                'perintah' => 'Mengenal musim',
                'aspek_perkembangan_id' => '3',
                'kategori_umur_id' => '9',
            ],
            [
                'id' => '185',
                'perintah' => 'Membantu pekerjaan di dapur',
                'aspek_perkembangan_id' => '3',
                'kategori_umur_id' => '9',
            ],
            [
                'id' => '186',
                'perintah' => 'Berpakaian sendiri tanpa dibantu',
                'aspek_perkembangan_id' => '4',
                'kategori_umur_id' => '9',
            ],
            [
                'id' => '187',
                'perintah' => 'Berperan dalam tugas rumah',
                'aspek_perkembangan_id' => '4',
                'kategori_umur_id' => '9',
            ],
            [
                'id' => '188',
                'perintah' => 'Interaksi teman sebaya',
                'aspek_perkembangan_id' => '4',
                'kategori_umur_id' => '9',
            ],
            [
                'id' => '189',
                'perintah' => 'Mendengar cerita anak',
                'aspek_perkembangan_id' => '4',
                'kategori_umur_id' => '9',
            ],
            [
                'id' => '190',
                'perintah' => 'Buat rencana jalan-jalan',
                'aspek_perkembangan_id' => '4',
                'kategori_umur_id' => '9',
            ],
            [
                'id' => '191',
                'perintah' => 'Mengikuti aturan / petunjuk permainan',
                'aspek_perkembangan_id' => '4',
                'kategori_umur_id' => '9',
            ],
            [
                'id' => '192',
                'perintah' => 'Membuat album keluarga',
                'aspek_perkembangan_id' => '4',
                'kategori_umur_id' => '9',
            ],
            [
                'id' => '193',
                'perintah' => 'Membuat boneka',
                'aspek_perkembangan_id' => '4',
                'kategori_umur_id' => '9',
            ],
            [
                'id' => '194',
                'perintah' => 'Menggambar orang',
                'aspek_perkembangan_id' => '4',
                'kategori_umur_id' => '9',
            ],
            [
                'id' => '195',
                'perintah' => 'Bermain kreatif dengan teman',
                'aspek_perkembangan_id' => '4',
                'kategori_umur_id' => '9',
            ],
            [
                'id' => '196',
                'perintah' => 'Bermain jual beli',
                'aspek_perkembangan_id' => '4',
                'kategori_umur_id' => '9',
            ],

            // --> KATEGORI UMUR 60-72 BULAN <--
            [
                'id' => '197',
                'perintah' => 'Berdiri 1 kaki 6 detik',
                'aspek_perkembangan_id' => '1',
                'kategori_umur_id' => '10',
            ],
            [
                'id' => '198',
                'perintah' => 'Berjalan dengan tumit',
                'aspek_perkembangan_id' => '1',
                'kategori_umur_id' => '10',
            ],
            [
                'id' => '199',
                'perintah' => 'Mencontoh',
                'aspek_perkembangan_id' => '2',
                'kategori_umur_id' => '10',
            ],
            [
                'id' => '200',
                'perintah' => 'Mengambar orang',
                'aspek_perkembangan_id' => '2',
                'kategori_umur_id' => '10',
            ],
            [
                'id' => '201',
                'perintah' => 'Mencontoh benda yang ditunjukkan',
                'aspek_perkembangan_id' => '2',
                'kategori_umur_id' => '10',
            ],
            [
                'id' => '202',
                'perintah' => 'Mengartikan 7 kata',
                'aspek_perkembangan_id' => '3',
                'kategori_umur_id' => '10',
            ],
            [
                'id' => '203',
                'perintah' => 'Menyebutkan 2 kata berlawanan',
                'aspek_perkembangan_id' => '3',
                'kategori_umur_id' => '10',
            ],
            [
                'id' => '204',
                'perintah' => 'Menghitung 5 kubus',
                'aspek_perkembangan_id' => '3',
                'kategori_umur_id' => '10',
            ],
            [
                'id' => '205',
                'perintah' => 'Mengambil makan',
                'aspek_perkembangan_id' => '4',
                'kategori_umur_id' => '10',
            ],
            [
                'id' => '206',
                'perintah' => 'Gosok gigi tanpa bantuan',
                'aspek_perkembangan_id' => '4',
                'kategori_umur_id' => '10',
            ],
            [
                'id' => '207',
                'perintah' => 'Bermain ular tangga',
                'aspek_perkembangan_id' => '4',
                'kategori_umur_id' => '10',
            ],
        ]);
    }
}
